'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Namespace Model

    Partial Public Class Actor
        Public Property Name As String
        Public Property thumb As String
    
        Public Overridable Property MoviesActors As ICollection(Of MoviesActor) = New HashSet(Of MoviesActor)
        Public Overridable Property TVShowActors As ICollection(Of TVShowActor) = New HashSet(Of TVShowActor)
        Public Overridable Property TVEpActors As ICollection(Of TVEpActor) = New HashSet(Of TVEpActor)
    
    End Class

End Namespace
