'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace Model

    Partial Public Class MediaEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=MediaEntities")
            MyBase.Configuration.LazyLoadingEnabled = False
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Actors() As DbSet(Of Actor)
        Public Overridable Property EmberFiles() As DbSet(Of EmberFile)
        Public Overridable Property ExcludeDirs() As DbSet(Of ExcludeDir)
        Public Overridable Property ExcludeFiles() As DbSet(Of ExcludeFile)
        Public Overridable Property ExcludeFilesInFolders() As DbSet(Of ExcludeFilesInFolder)
        Public Overridable Property Movies() As DbSet(Of Movie)
        Public Overridable Property MoviesActors() As DbSet(Of MoviesActor)
        Public Overridable Property MoviesAStreams() As DbSet(Of MoviesAStream)
        Public Overridable Property MoviesFanarts() As DbSet(Of MoviesFanart)
        Public Overridable Property MoviesPosters() As DbSet(Of MoviesPoster)
        Public Overridable Property MoviesSets() As DbSet(Of MoviesSet)
        Public Overridable Property MoviesSubs() As DbSet(Of MoviesSub)
        Public Overridable Property MoviesVStreams() As DbSet(Of MoviesVStream)
        Public Overridable Property OrigPaths() As DbSet(Of OrigPath)
        Public Overridable Property Sets() As DbSet(Of [Set])
        Public Overridable Property Sources() As DbSet(Of Source)
        Public Overridable Property TVAStreams() As DbSet(Of TVAStream)
        Public Overridable Property TVEpActors() As DbSet(Of TVEpActor)
        Public Overridable Property TVEpPaths() As DbSet(Of TVEpPath)
        Public Overridable Property TVEps() As DbSet(Of TVEp)
        Public Overridable Property TVSeasons() As DbSet(Of TVSeason)
        Public Overridable Property TVShowActors() As DbSet(Of TVShowActor)
        Public Overridable Property TVShows() As DbSet(Of TVShow)
        Public Overridable Property TVSources() As DbSet(Of TVSource)
        Public Overridable Property TVSubs() As DbSet(Of TVSub)
        Public Overridable Property TVVStreams() As DbSet(Of TVVStream)
    
    End Class

End Namespace
