'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Namespace Model

    Partial Public Class EmberFile
        Public Property OrigPath As String
        Public Property EmberPath As String
        Public Property Filename As String
        Public Property Hash As String
        Public Property Platform As String
        Public Property UseFile As Boolean
    
    End Class

End Namespace
