'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace Model

    Partial Public Class MediaEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=MediaEntities")
            MyBase.Configuration.LazyLoadingEnabled = False
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
    	    Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Property Actors() As DbSet(Of Actor)
        Public Property EmberFiles() As DbSet(Of EmberFile)
        Public Property ExcludeDirs() As DbSet(Of ExcludeDir)
        Public Property ExcludeFiles() As DbSet(Of ExcludeFile)
        Public Property ExcludeFilesInFolders() As DbSet(Of ExcludeFilesInFolder)
        Public Property Movies() As DbSet(Of Movie)
        Public Property MoviesActors() As DbSet(Of MoviesActor)
        Public Property MoviesAStreams() As DbSet(Of MoviesAStream)
        Public Property MoviesFanarts() As DbSet(Of MoviesFanart)
        Public Property MoviesPosters() As DbSet(Of MoviesPoster)
        Public Property MoviesSets() As DbSet(Of MoviesSet)
        Public Property MoviesSubs() As DbSet(Of MoviesSub)
        Public Property MoviesVStreams() As DbSet(Of MoviesVStream)
        Public Property OrigPaths() As DbSet(Of OrigPath)
        Public Property Sets() As DbSet(Of [Set])
        Public Property Sources() As DbSet(Of Source)
        Public Property TVAStreams() As DbSet(Of TVAStream)
        Public Property TVEpActors() As DbSet(Of TVEpActor)
        Public Property TVEpPaths() As DbSet(Of TVEpPath)
        Public Property TVEps() As DbSet(Of TVEp)
        Public Property TVSeasons() As DbSet(Of TVSeason)
        Public Property TVShowActors() As DbSet(Of TVShowActor)
        Public Property TVShows() As DbSet(Of TVShow)
        Public Property TVSources() As DbSet(Of TVSource)
        Public Property TVSubs() As DbSet(Of TVSub)
        Public Property TVVStreams() As DbSet(Of TVVStream)
    
    End Class

End Namespace
