'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Model

    Partial Public Class Movie
        Public Property ID As Long
        Public Property MoviePath As String
        Public Property Type As Nullable(Of Boolean)
        Public Property ListTitle As String
        Public Property HasPoster As Nullable(Of Boolean)
        Public Property HasFanart As Nullable(Of Boolean)
        Public Property HasNfo As Nullable(Of Boolean)
        Public Property HasTrailer As Nullable(Of Boolean)
        Public Property HasSub As Nullable(Of Boolean)
        Public Property HasExtra As Nullable(Of Boolean)
        Public Property IsNew As Nullable(Of Boolean)
        Public Property Mark As Nullable(Of Boolean)
        Public Property Source As String
        Public Property Imdb As String
        Public Property Lock As Boolean
        Public Property Title As String
        Public Property OriginalTitle As String
        Public Property Year As String
        Public Property Rating As String
        Public Property Votes As String
        Public Property MPAA As String
        Public Property Top250 As String
        Public Property Country As String
        Public Property Outline As String
        Public Property Plot As String
        Public Property Tagline As String
        Public Property Certification As String
        Public Property Genre As String
        Public Property Studio As String
        Public Property Runtime As String
        Public Property ReleaseDate As String
        Public Property Director As String
        Public Property Credits As String
        Public Property Playcount As String
        Public Property Watched As String
        Public Property Trailer As String
        Public Property PosterPath As String
        Public Property FanartPath As String
        Public Property ExtraPath As String
        Public Property NfoPath As String
        Public Property TrailerPath As String
        Public Property SubPath As String
        Public Property FanartURL As String
        Public Property UseFolder As Boolean
        Public Property OutOfTolerance As Nullable(Of Boolean)
        Public Property FileSource As String
        Public Property NeedsSave As Nullable(Of Boolean)
        Public Property SortTitle As String
        Public Property DateAdd As Nullable(Of Long)
    
        Public Overridable Property MoviesActors As ICollection(Of MoviesActor) = New HashSet(Of MoviesActor)
        Public Overridable Property MoviesAStreams As ICollection(Of MoviesAStream) = New HashSet(Of MoviesAStream)
        Public Overridable Property MoviesVStreams As ICollection(Of MoviesVStream) = New HashSet(Of MoviesVStream)
        Public Overridable Property MoviesSubs As ICollection(Of MoviesSub) = New HashSet(Of MoviesSub)
        Public Overridable Property MoviesSets As ICollection(Of MoviesSet) = New HashSet(Of MoviesSet)
        Public Overridable Property MoviesPosters As ICollection(Of MoviesPoster) = New HashSet(Of MoviesPoster)
        Public Overridable Property MoviesFanarts As ICollection(Of MoviesFanart) = New HashSet(Of MoviesFanart)
    
    End Class

End Namespace
