'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Namespace Model

    Partial Public Class MoviesSet
        Public Property MovieID As Long
        Public Property SetName As String
        Public Property SetOrder As String
    
        Public Overridable Property Movie As Movie
    
    End Class

End Namespace
