'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Namespace Model

    Partial Public Class Source
        Public Property ID As Long
        Public Property Name As String
        Public Property path As String
        Public Property Recursive As Boolean
        Public Property Foldername As Boolean
        Public Property [Single] As Boolean
        Public Property LastScan As String
    
    End Class

End Namespace
