'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Model

    Partial Public Class TVEpPath
        Public Property ID As Long
        Public Property FilePath As String
    
        Public Overridable Property TVEps As ICollection(Of TVEp) = New HashSet(Of TVEp)
    
    End Class

End Namespace
