'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Model

    Partial Public Class TVEp
        Public Property ID As Long
        Public Property TVShowID As Long
        Public Property Episode As Nullable(Of Long)
        Public Property Title As String
        Public Property HasPoster As Boolean
        Public Property HasFanart As Boolean
        Public Property HasNfo As Boolean
        Public Property IsNew As Nullable(Of Boolean)
        Public Property Mark As Boolean
        Public Property TVEpPathID As Long
        Public Property Source As String
        Public Property Lock As Boolean
        Public Property Season As Nullable(Of Long)
        Public Property Rating As String
        Public Property Plot As String
        Public Property Aired As String
        Public Property Director As String
        Public Property Credits As String
        Public Property PosterPath As String
        Public Property FanartPath As String
        Public Property NfoPath As String
        Public Property NeedsSave As Boolean
        Public Property Missing As Boolean
    
        Public Overridable Property TVEpActors As ICollection(Of TVEpActor) = New HashSet(Of TVEpActor)
        Public Overridable Property TVSeason As TVSeason
        Public Overridable Property TVShow As TVShow
        Public Overridable Property TVEpPath As TVEpPath
    
    End Class

End Namespace
