'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Namespace Model

    Partial Public Class TVEpActor
        Public Property TVEpID As Long
        Public Property ActorName As String
        Public Property Role As String
    
        Public Overridable Property TVEp As TVEp
        Public Overridable Property Actor As Actor
    
    End Class

End Namespace
