'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Namespace Model

    Partial Public Class TVSeason
        Public Property TVShowID As Long
        Public Property SeasonText As String
        Public Property Season As Long
        Public Property HasPoster As Boolean
        Public Property HasFanart As Boolean
        Public Property PosterPath As String
        Public Property FanartPath As String
        Public Property Lock As Boolean
        Public Property Mark As Boolean
        Public Property IsNew As Boolean
    
        Public Overridable Property TVShow As TVShow
        Public Overridable Property TVEps As ICollection(Of TVEp) = New HashSet(Of TVEp)
    
    End Class

End Namespace
