'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Model

    Partial Public Class TVSub
        Public Property TVEpID As Long
        Public Property StreamID As Long
        Public Property Subs_Language As String
        Public Property Subs_LongLanguage As String
    
    End Class

End Namespace
