'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Namespace Model

    Partial Public Class TVVStream
        Public Property TVEpID As Long
        Public Property StreamID As Long
        Public Property Video_Width As String
        Public Property Video_Height As String
        Public Property Video_Codec As String
        Public Property Video_Duration As String
        Public Property Video_ScanType As String
        Public Property Video_AspectDisplayRatio As String
        Public Property Video_Language As String
        Public Property Video_LongLanguage As String
    
    End Class

End Namespace
