'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace EmberResources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EmberMediaManger.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--
        '''### Anchor Help ###
        '''0 = none
        '''1 = Top
        '''2 = Bottom
        '''4 = Left
        '''8 = Right
        '''
        '''Can be combined by adding values. For example, the standard TopLeft anchor would
        '''be anchor code 5.
        '''
        '''### FontStyle Help ###
        '''0 = Regular
        '''1 = Bold
        '''2 = Italic
        '''4 = Underline
        '''8 = Strikeout
        '''
        '''Can be combined by adding values. For example, bold and underlined would be
        '''fontstyle code 5.
        '''--&gt;
        '''
        '''&lt;theme&gt;
        '''  &lt;toppanel&gt;
        '''    &lt;backcolor&gt;-2302756&lt;/backcolor&gt;
        '''    &lt;forecolor&gt;-16777216&lt;/forecolo [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property movie_Default() As String
            Get
                Return ResourceManager.GetString("movie_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''&lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Public ReadOnly Property MovieListFooter() As String
            Get
                Return ResourceManager.GetString("MovieListFooter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''&lt;head&gt;
        '''&lt;style type=&quot;text/css&quot;&gt;
        '''&lt;!--
        '''body {background: #FFFFFF; /* The background of the page will be colored white */}
        '''a:link {color: #000000; /* All unvisited links will be colored black */ }
        '''a:visited {color: #FF9900; /* All visited links will be colored tan */ }
        '''a:active {color: #FF0000; /* All active links will be colored red */}
        '''a:hover {color: #0000FF; background: #FFFF00;}
        '''/* When the mouse pointer is over the link the link will be colored blue
        '''and the background color of the link wi [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property MovieListHeader() As String
            Get
                Return ResourceManager.GetString("MovieListHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;td&gt;&lt;span style=&quot;color:darkblue;&quot;&gt;{0}&lt;/span&gt;&lt;/td&gt;.
        '''</summary>
        Public ReadOnly Property MovieListTableCol() As String
            Get
                Return ResourceManager.GetString("MovieListTableCol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/table&gt;
        '''&lt;/center&gt;.
        '''</summary>
        Public ReadOnly Property MovieListTableEnd() As String
            Get
                Return ResourceManager.GetString("MovieListTableEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;th style=&quot;text-align:left; &quot;&gt;{0}&lt;/th&gt;.
        '''</summary>
        Public ReadOnly Property MovieListTableHeader() As String
            Get
                Return ResourceManager.GetString("MovieListTableHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/tr&gt;.
        '''</summary>
        Public ReadOnly Property MovieListTableRowEnd() As String
            Get
                Return ResourceManager.GetString("MovieListTableRowEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''&lt;tr&gt;.
        '''</summary>
        Public ReadOnly Property MovieListTableRowStart() As String
            Get
                Return ResourceManager.GetString("MovieListTableRowStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;center&gt;
        '''&lt;table class=&quot;emm_table&quot;&gt;
        '''.
        '''</summary>
        Public ReadOnly Property MovieListTableStart() As String
            Get
                Return ResourceManager.GetString("MovieListTableStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Public ReadOnly Property Settings() As String
            Get
                Return ResourceManager.GetString("Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--
        '''### Anchor Help ###
        '''0 = none
        '''1 = Top
        '''2 = Bottom
        '''4 = Left
        '''8 = Right
        '''
        '''Can be combined by adding values. For example, the standard TopLeft anchor would
        '''be anchor code 5.
        '''
        '''### FontStyle Help ###
        '''0 = Regular
        '''1 = Bold
        '''2 = Italic
        '''4 = Underline
        '''8 = Strikeout
        '''
        '''Can be combined by adding values. For example, bold and underlined would be
        '''fontstyle code 5.
        '''--&gt;
        '''
        '''&lt;theme&gt;
        '''  &lt;toppanel&gt;
        '''    &lt;backcolor&gt;-2302756&lt;/backcolor&gt;
        '''    &lt;forecolor&gt;-16777216&lt;/forecolo [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property tvep_Default() As String
            Get
                Return ResourceManager.GetString("tvep_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;!--
        '''### Anchor Help ###
        '''0 = none
        '''1 = Top
        '''2 = Bottom
        '''4 = Left
        '''8 = Right
        '''
        '''Can be combined by adding values. For example, the standard TopLeft anchor would
        '''be anchor code 5.
        '''
        '''### FontStyle Help ###
        '''0 = Regular
        '''1 = Bold
        '''2 = Italic
        '''4 = Underline
        '''8 = Strikeout
        '''
        '''Can be combined by adding values. For example, bold and underlined would be
        '''fontstyle code 5.
        '''--&gt;
        '''
        '''&lt;theme&gt;
        '''  &lt;toppanel&gt;
        '''    &lt;backcolor&gt;-2302756&lt;/backcolor&gt;
        '''    &lt;forecolor&gt;-16777216&lt;/forecolo [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property tvshow_Default() As String
            Get
                Return ResourceManager.GetString("tvshow_Default", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
