'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MoviesSub
    Public Property MovieID As Long
    Public Property StreamID As Long
    Public Property Subs_Language As String
    Public Property Subs_LongLanguage As String
    Public Property Subs_Type As String
    Public Property Subs_Path As String

End Class
