'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TVAStream
    Public Property TVEpID As Long
    Public Property StreamID As Long
    Public Property Audio_Language As String
    Public Property Audio_LongLanguage As String
    Public Property Audio_Codec As String
    Public Property Audio_Channel As String

End Class
