'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TVShow
    Public Property ID As Long
    Public Property Title As String
    Public Property HasPoster As Boolean
    Public Property HasFanart As Boolean
    Public Property HasNfo As Boolean
    Public Property [New] As Nullable(Of Boolean)
    Public Property Mark As Boolean
    Public Property TVShowPath As String
    Public Property Source As String
    Public Property TVDB As String
    Public Property Lock As Boolean
    Public Property EpisodeGuide As String
    Public Property Plot As String
    Public Property Genre As String
    Public Property Premiered As String
    Public Property Studio As String
    Public Property MPAA As String
    Public Property Rating As String
    Public Property PosterPath As String
    Public Property FanartPath As String
    Public Property NfoPath As String
    Public Property NeedsSave As Boolean
    Public Property Language As String
    Public Property Ordering As Long

End Class
