'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Languages
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EmberMediaManger.Languages", GetType(Languages).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to And.
    '''</summary>
    Friend Shared ReadOnly Property _And() As String
        Get
            Return ResourceManager.GetString("_And", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Auto.
    '''</summary>
    Friend Shared ReadOnly Property _Auto() As String
        Get
            Return ResourceManager.GetString("_Auto", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Error.
    '''</summary>
    Friend Shared ReadOnly Property _Error() As String
        Get
            Return ResourceManager.GetString("_Error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Interface.
    '''</summary>
    Friend Shared ReadOnly Property _Interface() As String
        Get
            Return ResourceManager.GetString("_Interface", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to New.
    '''</summary>
    Friend Shared ReadOnly Property _New() As String
        Get
            Return ResourceManager.GetString("_New", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Or.
    '''</summary>
    Friend Shared ReadOnly Property _Or() As String
        Get
            Return ResourceManager.GetString("_Or", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to About Ember Media Manager.
    '''</summary>
    Friend Shared ReadOnly Property About_Ember_Media_Manager() As String
        Get
            Return ResourceManager.GetString("About_Ember_Media_Manager", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Actor.
    '''</summary>
    Friend Shared ReadOnly Property Actor() As String
        Get
            Return ResourceManager.GetString("Actor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Actor Name:.
    '''</summary>
    Friend Shared ReadOnly Property Actor_Name() As String
        Get
            Return ResourceManager.GetString("Actor_Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Actor Role:.
    '''</summary>
    Friend Shared ReadOnly Property Actor_Role() As String
        Get
            Return ResourceManager.GetString("Actor_Role", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Actor Thumb (URL):.
    '''</summary>
    Friend Shared ReadOnly Property Actor_Thumb_URL() As String
        Get
            Return ResourceManager.GetString("Actor_Thumb_URL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Add.
    '''</summary>
    Friend Shared ReadOnly Property Add() As String
        Get
            Return ResourceManager.GetString("Add", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Aired: {0}.
    '''</summary>
    Friend Shared ReadOnly Property Aired_Param() As String
        Get
            Return ResourceManager.GetString("Aired_Param", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Always Display Genre Text.
    '''</summary>
    Friend Shared ReadOnly Property Always_Display_Genre_Text() As String
        Get
            Return ResourceManager.GetString("Always_Display_Genre_Text", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Apply.
    '''</summary>
    Friend Shared ReadOnly Property Apply() As String
        Get
            Return ResourceManager.GetString("Apply", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are You Sure?.
    '''</summary>
    Friend Shared ReadOnly Property Are_You_Sure() As String
        Get
            Return ResourceManager.GetString("Are_You_Sure", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure you want to reset to the default list of movie filters?.
    '''</summary>
    Friend Shared ReadOnly Property Are_you_sure_you_want_to_reset_to_the_default_list_of_movie_filters() As String
        Get
            Return ResourceManager.GetString("Are_you_sure_you_want_to_reset_to_the_default_list_of_movie_filters", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure you want to reset to the default list of valid video extensions?.
    '''</summary>
    Friend Shared ReadOnly Property Are_you_sure_you_want_to_reset_to_the_default_list_of_valid_video_extensions() As String
        Get
            Return ResourceManager.GetString("Are_you_sure_you_want_to_reset_to_the_default_list_of_valid_video_extensions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ask On Click Scrape.
    '''</summary>
    Friend Shared ReadOnly Property Ask_On_Click_Scrape() As String
        Get
            Return ResourceManager.GetString("Ask_On_Click_Scrape", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Audio.
    '''</summary>
    Friend Shared ReadOnly Property Audio() As String
        Get
            Return ResourceManager.GetString("Audio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Audio Streams.
    '''</summary>
    Friend Shared ReadOnly Property Audio_Streams() As String
        Get
            Return ResourceManager.GetString("Audio_Streams", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Automatically Rename Files During Multi-Scraper.
    '''</summary>
    Friend Shared ReadOnly Property Automatically_Rename_Files_During_Multi_Scraper() As String
        Get
            Return ResourceManager.GetString("Automatically_Rename_Files_During_Multi_Scraper", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Automatically Rename Files During Single-Scraper.
    '''</summary>
    Friend Shared ReadOnly Property Automatically_Rename_Files_During_Single_Scraper() As String
        Get
            Return ResourceManager.GetString("Automatically_Rename_Files_During_Single_Scraper", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Automatically Resize:.
    '''</summary>
    Friend Shared ReadOnly Property Automatically_Resize() As String
        Get
            Return ResourceManager.GetString("Automatically_Resize", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Backdrops Folder.
    '''</summary>
    Friend Shared ReadOnly Property Backdrops_Folder() As String
        Get
            Return ResourceManager.GetString("Backdrops_Folder", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bulk &amp;Renamer.
    '''</summary>
    Friend Shared ReadOnly Property Bulk_Renamer() As String
        Get
            Return ResourceManager.GetString("Bulk_Renamer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to $1 = First Letter of the Title{0}$A = Audio{0}$B = Base Path{0}$C = Director{0}$D = Directory{0}$E = Sort Title{0}$F = File Name{0}$G = Genre (Follow with a space, dot or hyphen to change separator){0}$I = IMDB ID{0}$L = List Title{0}$M = MPAA{0}$O = OriginalTitle{0}$R = Resolution{0}$S = Source{0}$T = Title{0}$U = Country{0}$Y = Year{0}$X. (Replace Space with .){0}{{}} = Optional{0}$?aaa?bbb? = Replace aaa with bbb{0}$- = Remove previous char if next pattern does not have a value{0}$+ = Remove next char if [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property BulkRenameHelp() As String
        Get
            Return ResourceManager.GetString("BulkRenameHelp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to $1 = First Letter of the Title{0}$A = Audio{0}$B = Base Path{0}$C = Director{0}$D = Directory{0}$E = Sort Title{0}$F = File Name{0}$G = Genre (Follow with a space, dot or hyphen to change separator){0}$I = IMDB ID{0}$L = List Title{0}$M = MPAA{0}$O = OriginalTitle{0}$R = Resolution{0}$S = Source{0}$T = Title{0}$Y = Year{0}$X. (Replace Space with .){0}{{}} = Optional{0}$?aaa?bbb? = Replace aaa with bbb{0}$- = Remove previous char if next pattern does not have a value{0}$+ = Remove next char if previous patte [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property BulkRenamerHelp() As String
        Get
            Return ResourceManager.GetString("BulkRenamerHelp", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Caching.
    '''</summary>
    Friend Shared ReadOnly Property Caching() As String
        Get
            Return ResourceManager.GetString("Caching", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cancel.
    '''</summary>
    Friend Shared ReadOnly Property Cancel() As String
        Get
            Return ResourceManager.GetString("Cancel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cancel Scraper.
    '''</summary>
    Friend Shared ReadOnly Property Cancel_Scraper() As String
        Get
            Return ResourceManager.GetString("Cancel_Scraper", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Canceling Compilation....
    '''</summary>
    Friend Shared ReadOnly Property Canceling_Compilation() As String
        Get
            Return ResourceManager.GetString("Canceling_Compilation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Canceling Scraper....
    '''</summary>
    Friend Shared ReadOnly Property Canceling_Scraper() As String
        Get
            Return ResourceManager.GetString("Canceling_Scraper", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cast.
    '''</summary>
    Friend Shared ReadOnly Property Cast() As String
        Get
            Return ResourceManager.GetString("Cast", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Certification.
    '''</summary>
    Friend Shared ReadOnly Property Certification() As String
        Get
            Return ResourceManager.GetString("Certification", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Certification(s).
    '''</summary>
    Friend Shared ReadOnly Property Certifications() As String
        Get
            Return ResourceManager.GetString("Certifications", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change.
    '''</summary>
    Friend Shared ReadOnly Property Change() As String
        Get
            Return ResourceManager.GetString("Change", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Check for Extrathumbs.
    '''</summary>
    Friend Shared ReadOnly Property Check_for_Extrathumbs() As String
        Get
            Return ResourceManager.GetString("Check_for_Extrathumbs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Check for Fanart.
    '''</summary>
    Friend Shared ReadOnly Property Check_for_Fanart() As String
        Get
            Return ResourceManager.GetString("Check_for_Fanart", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Check for NFO.
    '''</summary>
    Friend Shared ReadOnly Property Check_for_NFO() As String
        Get
            Return ResourceManager.GetString("Check_for_NFO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Check for Poster.
    '''</summary>
    Friend Shared ReadOnly Property Check_for_Poster() As String
        Get
            Return ResourceManager.GetString("Check_for_Poster", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Check for Subs.
    '''</summary>
    Friend Shared ReadOnly Property Check_for_Subs() As String
        Get
            Return ResourceManager.GetString("Check_for_Subs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Check for Trailer.
    '''</summary>
    Friend Shared ReadOnly Property Check_for_Trailer() As String
        Get
            Return ResourceManager.GetString("Check_for_Trailer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Check for Updates.
    '''</summary>
    Friend Shared ReadOnly Property Check_for_Updates() As String
        Get
            Return ResourceManager.GetString("Check_for_Updates", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Check Title Match Confidence.
    '''</summary>
    Friend Shared ReadOnly Property Check_Title_Match_Confidence() As String
        Get
            Return ResourceManager.GetString("Check_Title_Match_Confidence", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Clean Files.
    '''</summary>
    Friend Shared ReadOnly Property Clean_Files() As String
        Get
            Return ResourceManager.GetString("Clean_Files", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Clear Filters.
    '''</summary>
    Friend Shared ReadOnly Property Clear_Filters() As String
        Get
            Return ResourceManager.GetString("Clear_Filters", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Close.
    '''</summary>
    Friend Shared ReadOnly Property Close() As String
        Get
            Return ResourceManager.GetString("Close", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Compiling Movie List....
    '''</summary>
    Friend Shared ReadOnly Property Compiling_Movie_List() As String
        Get
            Return ResourceManager.GetString("Compiling_Movie_List", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Configure Ember&apos;s appearance and operation..
    '''</summary>
    Friend Shared ReadOnly Property Configure_Ember_appearance_and_operation() As String
        Get
            Return ResourceManager.GetString("Configure_Ember_appearance_and_operation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Convert Names to Proper Case.
    '''</summary>
    Friend Shared ReadOnly Property Convert_Names_to_Proper_Case() As String
        Get
            Return ResourceManager.GetString("Convert_Names_to_Proper_Case", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Credentials.
    '''</summary>
    Friend Shared ReadOnly Property Credentials() As String
        Get
            Return ResourceManager.GetString("Credentials", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current Image:.
    '''</summary>
    Friend Shared ReadOnly Property Current_Image() As String
        Get
            Return ResourceManager.GetString("Current_Image", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Default Renaming Patterns.
    '''</summary>
    Friend Shared ReadOnly Property Default_Renaming_Patterns() As String
        Get
            Return ResourceManager.GetString("Default_Renaming_Patterns", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete All Existing.
    '''</summary>
    Friend Shared ReadOnly Property Delete_All_Existing() As String
        Get
            Return ResourceManager.GetString("Delete_All_Existing", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Director.
    '''</summary>
    Friend Shared ReadOnly Property Director() As String
        Get
            Return ResourceManager.GetString("Director", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Display Image Dimensions.
    '''</summary>
    Friend Shared ReadOnly Property Display_Image_Dimensions() As String
        Get
            Return ResourceManager.GetString("Display_Image_Dimensions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Display Only Movies That Will Be Renamed.
    '''</summary>
    Friend Shared ReadOnly Property Display_Only_Movies_That_Will_Be_Renamed() As String
        Get
            Return ResourceManager.GetString("Display_Only_Movies_That_Will_Be_Renamed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Display Year in List Title.
    '''</summary>
    Friend Shared ReadOnly Property Display_Year_in_List_Title() As String
        Get
            Return ResourceManager.GetString("Display_Year_in_List_Title", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Do Not Display Fanart.
    '''</summary>
    Friend Shared ReadOnly Property Do_Not_Display_Fanart() As String
        Get
            Return ResourceManager.GetString("Do_Not_Display_Fanart", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Do Not Display Poster.
    '''</summary>
    Friend Shared ReadOnly Property Do_Not_Display_Poster() As String
        Get
            Return ResourceManager.GetString("Do_Not_Display_Poster", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Do Not Save URLs to Nfo.
    '''</summary>
    Friend Shared ReadOnly Property Do_Not_Save_URLs_to_Nfo() As String
        Get
            Return ResourceManager.GetString("Do_Not_Save_URLs_to_Nfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Domain:.
    '''</summary>
    Friend Shared ReadOnly Property Domain() As String
        Get
            Return ResourceManager.GetString("Domain", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Download All Fanart Images of the Following Size as Extrathumbs:.
    '''</summary>
    Friend Shared ReadOnly Property Download_All_Fanart_Images_of_the_Following_Size_as_Extrathumbs() As String
        Get
            Return ResourceManager.GetString("Download_All_Fanart_Images_of_the_Following_Size_as_Extrathumbs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Downloading Fullsize Fanart Image....
    '''</summary>
    Friend Shared ReadOnly Property Downloading_Fullsize_Fanart_Image() As String
        Get
            Return ResourceManager.GetString("Downloading_Fullsize_Fanart_Image", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to (Down)Loading New Images....
    '''</summary>
    Friend Shared ReadOnly Property DownLoading_New_Images() As String
        Get
            Return ResourceManager.GetString("DownLoading_New_Images", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Duplicates.
    '''</summary>
    Friend Shared ReadOnly Property Duplicates() As String
        Get
            Return ResourceManager.GetString("Duplicates", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Each name must be unique.
    '''</summary>
    Friend Shared ReadOnly Property Each_name_must_be_unique() As String
        Get
            Return ResourceManager.GetString("Each_name_must_be_unique", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit.
    '''</summary>
    Friend Shared ReadOnly Property Edit() As String
        Get
            Return ResourceManager.GetString("Edit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit Actor.
    '''</summary>
    Friend Shared ReadOnly Property Edit_Actor() As String
        Get
            Return ResourceManager.GetString("Edit_Actor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit Episode.
    '''</summary>
    Friend Shared ReadOnly Property Edit_Episode() As String
        Get
            Return ResourceManager.GetString("Edit_Episode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Edit the details for the selected episode..
    '''</summary>
    Friend Shared ReadOnly Property Edit_the_details_for_the_selected_episode() As String
        Get
            Return ResourceManager.GetString("Edit_the_details_for_the_selected_episode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ember Media Manager.
    '''</summary>
    Friend Shared ReadOnly Property Ember_Media_Manager() As String
        Get
            Return ResourceManager.GetString("Ember_Media_Manager", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ember Media Manager is already running..
    '''</summary>
    Friend Shared ReadOnly Property Ember_Media_Manager_is_already_running() As String
        Get
            Return ResourceManager.GetString("Ember_Media_Manager_is_already_running", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enable Actors Cache.
    '''</summary>
    Friend Shared ReadOnly Property Enable_Actors_Cache() As String
        Get
            Return ResourceManager.GetString("Enable_Actors_Cache", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enable Bulk Renamer Tool.
    '''</summary>
    Friend Shared ReadOnly Property Enable_Bulk_Renamer_Tool() As String
        Get
            Return ResourceManager.GetString("Enable_Bulk_Renamer_Tool", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enable Click Scrape.
    '''</summary>
    Friend Shared ReadOnly Property Enable_Click_Scrape() As String
        Get
            Return ResourceManager.GetString("Enable_Click_Scrape", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enable Credentials.
    '''</summary>
    Friend Shared ReadOnly Property Enable_Credentials() As String
        Get
            Return ResourceManager.GetString("Enable_Credentials", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enable Generic Rename Module.
    '''</summary>
    Friend Shared ReadOnly Property Enable_Generic_Rename_Module() As String
        Get
            Return ResourceManager.GetString("Enable_Generic_Rename_Module", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enable Panel Animation.
    '''</summary>
    Friend Shared ReadOnly Property Enable_Panel_Animation() As String
        Get
            Return ResourceManager.GetString("Enable_Panel_Animation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enable Proxy.
    '''</summary>
    Friend Shared ReadOnly Property Enable_Proxy() As String
        Get
            Return ResourceManager.GetString("Enable_Proxy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enable Real Time synchronization.
    '''</summary>
    Friend Shared ReadOnly Property Enable_Real_Time_synchronization() As String
        Get
            Return ResourceManager.GetString("Enable_Real_Time_synchronization", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enable Trailer Support.
    '''</summary>
    Friend Shared ReadOnly Property Enable_Trailer_Support() As String
        Get
            Return ResourceManager.GetString("Enable_Trailer_Support", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enabled.
    '''</summary>
    Friend Shared ReadOnly Property Enabled() As String
        Get
            Return ResourceManager.GetString("Enabled", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enter the new Language.
    '''</summary>
    Friend Shared ReadOnly Property Enter_the_new_Language() As String
        Get
            Return ResourceManager.GetString("Enter_the_new_Language", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Episode.
    '''</summary>
    Friend Shared ReadOnly Property Episode() As String
        Get
            Return ResourceManager.GetString("Episode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Episode Theme.
    '''</summary>
    Friend Shared ReadOnly Property Episode_Theme() As String
        Get
            Return ResourceManager.GetString("Episode_Theme", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Error: .
    '''</summary>
    Friend Shared ReadOnly Property Error__() As String
        Get
            Return ResourceManager.GetString("Error__", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Error FileInfo.
    '''</summary>
    Friend Shared ReadOnly Property Error_FileInfo() As String
        Get
            Return ResourceManager.GetString("Error_FileInfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Expert.
    '''</summary>
    Friend Shared ReadOnly Property Expert() As String
        Get
            Return ResourceManager.GetString("Expert", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Export Movie List.
    '''</summary>
    Friend Shared ReadOnly Property Export_Movie_List() As String
        Get
            Return ResourceManager.GetString("Export_Movie_List", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Extract During Scrapers.
    '''</summary>
    Friend Shared ReadOnly Property Extract_During_Scrapers() As String
        Get
            Return ResourceManager.GetString("Extract_During_Scrapers", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Extrathumbs.
    '''</summary>
    Friend Shared ReadOnly Property Extrathumbs() As String
        Get
            Return ResourceManager.GetString("Extrathumbs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Fanart.
    '''</summary>
    Friend Shared ReadOnly Property Fanart() As String
        Get
            Return ResourceManager.GetString("Fanart", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File Extension.
    '''</summary>
    Friend Shared ReadOnly Property File_Extension() As String
        Get
            Return ResourceManager.GetString("File_Extension", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File Path.
    '''</summary>
    Friend Shared ReadOnly Property File_Path() As String
        Get
            Return ResourceManager.GetString("File_Path", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to File Pattern.
    '''</summary>
    Friend Shared ReadOnly Property File_Pattern() As String
        Get
            Return ResourceManager.GetString("File_Pattern", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Filename.
    '''</summary>
    Friend Shared ReadOnly Property Filename() As String
        Get
            Return ResourceManager.GetString("Filename", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Files Pattern.
    '''</summary>
    Friend Shared ReadOnly Property Files_Pattern() As String
        Get
            Return ResourceManager.GetString("Files_Pattern", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Filters.
    '''</summary>
    Friend Shared ReadOnly Property Filters() As String
        Get
            Return ResourceManager.GetString("Filters", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Folder/File Name Filters.
    '''</summary>
    Friend Shared ReadOnly Property Folder_File_Name_Filters() As String
        Get
            Return ResourceManager.GetString("Folder_File_Name_Filters", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Folder Name.
    '''</summary>
    Friend Shared ReadOnly Property Folder_Name() As String
        Get
            Return ResourceManager.GetString("Folder_Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Folder Pattern (for Multiple movies in Folder).
    '''</summary>
    Friend Shared ReadOnly Property Folder_Pattern__for_Multiple_movies_in_Folder() As String
        Get
            Return ResourceManager.GetString("Folder_Pattern__for_Multiple_movies_in_Folder", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Folder Pattern (for Single movie in Folder).
    '''</summary>
    Friend Shared ReadOnly Property Folder_Pattern_for_Single_movie_in_Folder() As String
        Get
            Return ResourceManager.GetString("Folder_Pattern_for_Single_movie_in_Folder", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Folders Pattern.
    '''</summary>
    Friend Shared ReadOnly Property Folders_Pattern() As String
        Get
            Return ResourceManager.GetString("Folders_Pattern", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to General.
    '''</summary>
    Friend Shared ReadOnly Property General() As String
        Get
            Return ResourceManager.GetString("General", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Genre.
    '''</summary>
    Friend Shared ReadOnly Property Genre() As String
        Get
            Return ResourceManager.GetString("Genre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Genre Language Filter.
    '''</summary>
    Friend Shared ReadOnly Property Genre_Language_Filter() As String
        Get
            Return ResourceManager.GetString("Genre_Language_Filter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Genres.
    '''</summary>
    Friend Shared ReadOnly Property Genres() As String
        Get
            Return ResourceManager.GetString("Genres", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Genres Filter.
    '''</summary>
    Friend Shared ReadOnly Property Genres_Filter() As String
        Get
            Return ResourceManager.GetString("Genres_Filter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Genres for {0}.
    '''</summary>
    Friend Shared ReadOnly Property Genres_for_Param() As String
        Get
            Return ResourceManager.GetString("Genres_for_Param", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Get During Automated Scrapers.
    '''</summary>
    Friend Shared ReadOnly Property Get_During_Automated_Scrapers() As String
        Get
            Return ResourceManager.GetString("Get_During_Automated_Scrapers", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Get During Single Scrape.
    '''</summary>
    Friend Shared ReadOnly Property Get_During_Single_Scrape() As String
        Get
            Return ResourceManager.GetString("Get_During_Single_Scrape", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Get on Single Scrape.
    '''</summary>
    Friend Shared ReadOnly Property Get_on_Single_Scrape() As String
        Get
            Return ResourceManager.GetString("Get_on_Single_Scrape", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Height:.
    '''</summary>
    Friend Shared ReadOnly Property Height() As String
        Get
            Return ResourceManager.GetString("Height", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Help.
    '''</summary>
    Friend Shared ReadOnly Property Help() As String
        Get
            Return ResourceManager.GetString("Help", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hide Extrathumb Column.
    '''</summary>
    Friend Shared ReadOnly Property Hide_Extrathumb_Column() As String
        Get
            Return ResourceManager.GetString("Hide_Extrathumb_Column", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hide Fanart Column.
    '''</summary>
    Friend Shared ReadOnly Property Hide_Fanart_Column() As String
        Get
            Return ResourceManager.GetString("Hide_Fanart_Column", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hide Info Column.
    '''</summary>
    Friend Shared ReadOnly Property Hide_Info_Column() As String
        Get
            Return ResourceManager.GetString("Hide_Info_Column", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hide Poster Column.
    '''</summary>
    Friend Shared ReadOnly Property Hide_Poster_Column() As String
        Get
            Return ResourceManager.GetString("Hide_Poster_Column", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hide Sub Column.
    '''</summary>
    Friend Shared ReadOnly Property Hide_Sub_Column() As String
        Get
            Return ResourceManager.GetString("Hide_Sub_Column", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hide Trailer Column.
    '''</summary>
    Friend Shared ReadOnly Property Hide_Trailer_Column() As String
        Get
            Return ResourceManager.GetString("Hide_Trailer_Column", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to (If unchecked, non-conforming nfos will be renamed to &lt;filename&gt;.info).
    '''</summary>
    Friend Shared ReadOnly Property If_unchecked_non_conforming_nfos_will_be_renamed() As String
        Get
            Return ResourceManager.GetString("If_unchecked_non_conforming_nfos_will_be_renamed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Images.
    '''</summary>
    Friend Shared ReadOnly Property Images() As String
        Get
            Return ResourceManager.GetString("Images", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to IMDB ID.
    '''</summary>
    Friend Shared ReadOnly Property IMDB_ID() As String
        Get
            Return ResourceManager.GetString("IMDB_ID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Include Folder Name in Source Type Check.
    '''</summary>
    Friend Shared ReadOnly Property Include_Folder_Name_in_Source_Type_Check() As String
        Get
            Return ResourceManager.GetString("Include_Folder_Name_in_Source_Type_Check", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Info.
    '''</summary>
    Friend Shared ReadOnly Property Info() As String
        Get
            Return ResourceManager.GetString("Info", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Interface Language:.
    '''</summary>
    Friend Shared ReadOnly Property Interface_Language() As String
        Get
            Return ResourceManager.GetString("Interface_Language", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid URL.
    '''</summary>
    Friend Shared ReadOnly Property Invalid_URL() As String
        Get
            Return ResourceManager.GetString("Invalid_URL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Languages.
    '''</summary>
    Friend Shared ReadOnly Property Languages() As String
        Get
            Return ResourceManager.GetString("Languages", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Large.
    '''</summary>
    Friend Shared ReadOnly Property Large() As String
        Get
            Return ResourceManager.GetString("Large", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Loading Current Images....
    '''</summary>
    Friend Shared ReadOnly Property Loading_Current_Images() As String
        Get
            Return ResourceManager.GetString("Loading_Current_Images", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lock.
    '''</summary>
    Friend Shared ReadOnly Property Lock() As String
        Get
            Return ResourceManager.GetString("Lock", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Lock All.
    '''</summary>
    Friend Shared ReadOnly Property Lock_All() As String
        Get
            Return ResourceManager.GetString("Lock_All", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Locked.
    '''</summary>
    Friend Shared ReadOnly Property Locked() As String
        Get
            Return ResourceManager.GetString("Locked", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Log Errors to File.
    '''</summary>
    Friend Shared ReadOnly Property Log_Errors_to_File() As String
        Get
            Return ResourceManager.GetString("Log_Errors_to_File", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Manual.
    '''</summary>
    Friend Shared ReadOnly Property Manual() As String
        Get
            Return ResourceManager.GetString("Manual", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Manual Rename.
    '''</summary>
    Friend Shared ReadOnly Property Manual_Rename() As String
        Get
            Return ResourceManager.GetString("Manual_Rename", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Map Media Source by File Extension.
    '''</summary>
    Friend Shared ReadOnly Property Map_Media_Source_by_File_Extension() As String
        Get
            Return ResourceManager.GetString("Map_Media_Source_by_File_Extension", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mapped Codec.
    '''</summary>
    Friend Shared ReadOnly Property Mapped_Codec() As String
        Get
            Return ResourceManager.GetString("Mapped_Codec", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mark.
    '''</summary>
    Friend Shared ReadOnly Property Mark() As String
        Get
            Return ResourceManager.GetString("Mark", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mark New Movies.
    '''</summary>
    Friend Shared ReadOnly Property Mark_New_Movies() As String
        Get
            Return ResourceManager.GetString("Mark_New_Movies", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Marked.
    '''</summary>
    Friend Shared ReadOnly Property Marked() As String
        Get
            Return ResourceManager.GetString("Marked", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Matches ({0}).
    '''</summary>
    Friend Shared ReadOnly Property Matches_WithParam() As String
        Get
            Return ResourceManager.GetString("Matches_WithParam", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Max Height:.
    '''</summary>
    Friend Shared ReadOnly Property Max_Height() As String
        Get
            Return ResourceManager.GetString("Max_Height", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Media List Options.
    '''</summary>
    Friend Shared ReadOnly Property Media_List_Options() As String
        Get
            Return ResourceManager.GetString("Media_List_Options", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mediainfo Codec.
    '''</summary>
    Friend Shared ReadOnly Property Mediainfo_Codec() As String
        Get
            Return ResourceManager.GetString("Mediainfo_Codec", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Medium.
    '''</summary>
    Friend Shared ReadOnly Property Medium() As String
        Get
            Return ResourceManager.GetString("Medium", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Meta Data.
    '''</summary>
    Friend Shared ReadOnly Property Meta_Data() As String
        Get
            Return ResourceManager.GetString("Meta_Data", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Miscellaneous.
    '''</summary>
    Friend Shared ReadOnly Property Miscellaneous() As String
        Get
            Return ResourceManager.GetString("Miscellaneous", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Miscellaneous Options.
    '''</summary>
    Friend Shared ReadOnly Property Miscellaneous_Options() As String
        Get
            Return ResourceManager.GetString("Miscellaneous_Options", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Mismatch Tolerance:.
    '''</summary>
    Friend Shared ReadOnly Property Mismatch_Tolerance() As String
        Get
            Return ResourceManager.GetString("Mismatch_Tolerance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to  [MISSING].
    '''</summary>
    Friend Shared ReadOnly Property MISSING() As String
        Get
            Return ResourceManager.GetString("MISSING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Missing Items.
    '''</summary>
    Friend Shared ReadOnly Property Missing_Items() As String
        Get
            Return ResourceManager.GetString("Missing_Items", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Missing Items Filter.
    '''</summary>
    Friend Shared ReadOnly Property Missing_Items_Filter() As String
        Get
            Return ResourceManager.GetString("Missing_Items_Filter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Modifier.
    '''</summary>
    Friend Shared ReadOnly Property Modifier() As String
        Get
            Return ResourceManager.GetString("Modifier", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Movie Theme.
    '''</summary>
    Friend Shared ReadOnly Property Movie_Theme() As String
        Get
            Return ResourceManager.GetString("Movie_Theme", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Movies.
    '''</summary>
    Friend Shared ReadOnly Property Movies() As String
        Get
            Return ResourceManager.GetString("Movies", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to MPAA.
    '''</summary>
    Friend Shared ReadOnly Property MPAA() As String
        Get
            Return ResourceManager.GetString("MPAA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &gt;&gt; Multiple &lt;&lt;.
    '''</summary>
    Friend Shared ReadOnly Property Multiple() As String
        Get
            Return ResourceManager.GetString("Multiple", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Music By.
    '''</summary>
    Friend Shared ReadOnly Property Music_By() As String
        Get
            Return ResourceManager.GetString("Music_By", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to New Actor.
    '''</summary>
    Friend Shared ReadOnly Property New_Actor() As String
        Get
            Return ResourceManager.GetString("New_Actor", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to New Language.
    '''</summary>
    Friend Shared ReadOnly Property New_Language() As String
        Get
            Return ResourceManager.GetString("New_Language", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nfo.
    '''</summary>
    Friend Shared ReadOnly Property Nfo() As String
        Get
            Return ResourceManager.GetString("Nfo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &gt;&gt; No Item Selected &lt;&lt;.
    '''</summary>
    Friend Shared ReadOnly Property No_Item_Selected() As String
        Get
            Return ResourceManager.GetString("No_Item_Selected", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No Matches Found.
    '''</summary>
    Friend Shared ReadOnly Property No_Matches_Found() As String
        Get
            Return ResourceManager.GetString("No_Matches_Found", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No Spoilers.
    '''</summary>
    Friend Shared ReadOnly Property No_Spoilers() As String
        Get
            Return ResourceManager.GetString("No_Spoilers", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No Stack Extensions.
    '''</summary>
    Friend Shared ReadOnly Property No_Stack_Extensions() As String
        Get
            Return ResourceManager.GetString("No_Stack_Extensions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No Thumb URL Specified.
    '''</summary>
    Friend Shared ReadOnly Property No_Thumb_URL_Specified() As String
        Get
            Return ResourceManager.GetString("No_Thumb_URL_Specified", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to None.
    '''</summary>
    Friend Shared ReadOnly Property None() As String
        Get
            Return ResourceManager.GetString("None", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Number To Create:.
    '''</summary>
    Friend Shared ReadOnly Property Number_To_Create() As String
        Get
            Return ResourceManager.GetString("Number_To_Create", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to OK.
    '''</summary>
    Friend Shared ReadOnly Property OK() As String
        Get
            Return ResourceManager.GetString("OK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to On Error.
    '''</summary>
    Friend Shared ReadOnly Property On_Error() As String
        Get
            Return ResourceManager.GetString("On_Error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to On Movie Scraped.
    '''</summary>
    Friend Shared ReadOnly Property On_Movie_Scraped() As String
        Get
            Return ResourceManager.GetString("On_Movie_Scraped", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to On New Episode Added.
    '''</summary>
    Friend Shared ReadOnly Property On_New_Episode_Added() As String
        Get
            Return ResourceManager.GetString("On_New_Episode_Added", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to On New Movie Added.
    '''</summary>
    Friend Shared ReadOnly Property On_New_Movie_Added() As String
        Get
            Return ResourceManager.GetString("On_New_Movie_Added", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Only.
    '''</summary>
    Friend Shared ReadOnly Property Only() As String
        Get
            Return ResourceManager.GetString("Only", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Only Get URLs When Scraping.
    '''</summary>
    Friend Shared ReadOnly Property Only_Get_URLs_When_Scraping() As String
        Get
            Return ResourceManager.GetString("Only_Get_URLs_When_Scraping", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Original Title.
    '''</summary>
    Friend Shared ReadOnly Property Original_Title() As String
        Get
            Return ResourceManager.GetString("Original_Title", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Other Crew.
    '''</summary>
    Friend Shared ReadOnly Property Other_Crew() As String
        Get
            Return ResourceManager.GetString("Other_Crew", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Out of Tolerance.
    '''</summary>
    Friend Shared ReadOnly Property Out_of_Tolerance() As String
        Get
            Return ResourceManager.GetString("Out_of_Tolerance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Overwrite Existing.
    '''</summary>
    Friend Shared ReadOnly Property Overwrite_Existing() As String
        Get
            Return ResourceManager.GetString("Overwrite_Existing", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Overwrite Non-conforming nfos.
    '''</summary>
    Friend Shared ReadOnly Property Overwrite_Non_conforming_nfos() As String
        Get
            Return ResourceManager.GetString("Overwrite_Non_conforming_nfos", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Padding.
    '''</summary>
    Friend Shared ReadOnly Property Padding() As String
        Get
            Return ResourceManager.GetString("Padding", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Password:.
    '''</summary>
    Friend Shared ReadOnly Property Password() As String
        Get
            Return ResourceManager.GetString("Password", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Persistent Image Cache.
    '''</summary>
    Friend Shared ReadOnly Property Persistent_Image_Cache() As String
        Get
            Return ResourceManager.GetString("Persistent_Image_Cache", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please Enter a Port.
    '''</summary>
    Friend Shared ReadOnly Property Please_Enter_a_Port() As String
        Get
            Return ResourceManager.GetString("Please_Enter_a_Port", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please Enter a Unique Name.
    '''</summary>
    Friend Shared ReadOnly Property Please_Enter_a_Unique_Name() As String
        Get
            Return ResourceManager.GetString("Please_Enter_a_Unique_Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please enter a URL to verify..
    '''</summary>
    Friend Shared ReadOnly Property Please_enter_a_URL_to_verify() As String
        Get
            Return ResourceManager.GetString("Please_enter_a_URL_to_verify", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please Enter an IP.
    '''</summary>
    Friend Shared ReadOnly Property Please_Enter_an_IP() As String
        Get
            Return ResourceManager.GetString("Please_Enter_an_IP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Plot.
    '''</summary>
    Friend Shared ReadOnly Property Plot() As String
        Get
            Return ResourceManager.GetString("Plot", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Plot Outline.
    '''</summary>
    Friend Shared ReadOnly Property Plot_Outline() As String
        Get
            Return ResourceManager.GetString("Plot_Outline", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Poster.
    '''</summary>
    Friend Shared ReadOnly Property Poster() As String
        Get
            Return ResourceManager.GetString("Poster", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Preferred Quality:.
    '''</summary>
    Friend Shared ReadOnly Property Preferred_Quality() As String
        Get
            Return ResourceManager.GetString("Preferred_Quality", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Preferred Size:.
    '''</summary>
    Friend Shared ReadOnly Property Preferred_Size() As String
        Get
            Return ResourceManager.GetString("Preferred_Size", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Premiered: {0}.
    '''</summary>
    Friend Shared ReadOnly Property Premiered_Param() As String
        Get
            Return ResourceManager.GetString("Premiered_Param", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Producers.
    '''</summary>
    Friend Shared ReadOnly Property Producers() As String
        Get
            Return ResourceManager.GetString("Producers", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Proxy.
    '''</summary>
    Friend Shared ReadOnly Property Proxy() As String
        Get
            Return ResourceManager.GetString("Proxy", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Proxy Port:.
    '''</summary>
    Friend Shared ReadOnly Property Proxy_Port() As String
        Get
            Return ResourceManager.GetString("Proxy_Port", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Proxy URL:.
    '''</summary>
    Friend Shared ReadOnly Property Proxy_URL() As String
        Get
            Return ResourceManager.GetString("Proxy_URL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quality:.
    '''</summary>
    Friend Shared ReadOnly Property Quality() As String
        Get
            Return ResourceManager.GetString("Quality", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Rating:.
    '''</summary>
    Friend Shared ReadOnly Property Rating() As String
        Get
            Return ResourceManager.GetString("Rating", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Refresh.
    '''</summary>
    Friend Shared ReadOnly Property Refresh() As String
        Get
            Return ResourceManager.GetString("Refresh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Release Date.
    '''</summary>
    Friend Shared ReadOnly Property Release_Date() As String
        Get
            Return ResourceManager.GetString("Release_Date", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Remove.
    '''</summary>
    Friend Shared ReadOnly Property Remove() As String
        Get
            Return ResourceManager.GetString("Remove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Remove Language.
    '''</summary>
    Friend Shared ReadOnly Property Remove_Language() As String
        Get
            Return ResourceManager.GetString("Remove_Language", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Remove Selected.
    '''</summary>
    Friend Shared ReadOnly Property Remove_Selected() As String
        Get
            Return ResourceManager.GetString("Remove_Selected", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Rename.
    '''</summary>
    Friend Shared ReadOnly Property Rename() As String
        Get
            Return ResourceManager.GetString("Rename", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Rename movies and files.
    '''</summary>
    Friend Shared ReadOnly Property Rename_movies_and_files() As String
        Get
            Return ResourceManager.GetString("Rename_movies_and_files", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Renaming....
    '''</summary>
    Friend Shared ReadOnly Property Renaming() As String
        Get
            Return ResourceManager.GetString("Renaming", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Renaming Directory/Files....
    '''</summary>
    Friend Shared ReadOnly Property Renaming_Directory_Files() As String
        Get
            Return ResourceManager.GetString("Renaming_Directory_Files", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Runtime: {0}.
    '''</summary>
    Friend Shared ReadOnly Property Runtime() As String
        Get
            Return ResourceManager.GetString("Runtime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Scraper Fields - Scraper specific.
    '''</summary>
    Friend Shared ReadOnly Property Scraper_Fields_Scraper_specific() As String
        Get
            Return ResourceManager.GetString("Scraper_Fields_Scraper_specific", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Scraping data.
    '''</summary>
    Friend Shared ReadOnly Property Scraping_data() As String
        Get
            Return ResourceManager.GetString("Scraping_data", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Search Results - .
    '''</summary>
    Friend Shared ReadOnly Property Search_Results() As String
        Get
            Return ResourceManager.GetString("Search_Results", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Search String.
    '''</summary>
    Friend Shared ReadOnly Property Search_String() As String
        Get
            Return ResourceManager.GetString("Search_String", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Season: {0}, Episode: {1}.
    '''</summary>
    Friend Shared ReadOnly Property SeasonEpisode_Param() As String
        Get
            Return ResourceManager.GetString("SeasonEpisode_Param", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Selected Items: {0}.
    '''</summary>
    Friend Shared ReadOnly Property Selected_Items_Param() As String
        Get
            Return ResourceManager.GetString("Selected_Items_Param", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Send Notifications.
    '''</summary>
    Friend Shared ReadOnly Property Send_Notifications() As String
        Get
            Return ResourceManager.GetString("Send_Notifications", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Set Defaults.
    '''</summary>
    Friend Shared ReadOnly Property Set_Defaults() As String
        Get
            Return ResourceManager.GetString("Set_Defaults", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Setting Defaults....
    '''</summary>
    Friend Shared ReadOnly Property Setting_Defaults() As String
        Get
            Return ResourceManager.GetString("Setting_Defaults", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Settings.
    '''</summary>
    Friend Shared ReadOnly Property Settings() As String
        Get
            Return ResourceManager.GetString("Settings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Show.
    '''</summary>
    Friend Shared ReadOnly Property Show() As String
        Get
            Return ResourceManager.GetString("Show", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Size: {0}x{1}.
    '''</summary>
    Friend Shared ReadOnly Property Size_Param() As String
        Get
            Return ResourceManager.GetString("Size_Param", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sizing (Extracted Frames).
    '''</summary>
    Friend Shared ReadOnly Property Sizing_Extracted_Frames() As String
        Get
            Return ResourceManager.GetString("Sizing_Extracted_Frames", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Small.
    '''</summary>
    Friend Shared ReadOnly Property Small() As String
        Get
            Return ResourceManager.GetString("Small", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sort Tokens to Ignore.
    '''</summary>
    Friend Shared ReadOnly Property Sort_Tokens_to_Ignore() As String
        Get
            Return ResourceManager.GetString("Sort_Tokens_to_Ignore", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Source.
    '''</summary>
    Friend Shared ReadOnly Property Source() As String
        Get
            Return ResourceManager.GetString("Source", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Source Name.
    '''</summary>
    Friend Shared ReadOnly Property Source_Name() As String
        Get
            Return ResourceManager.GetString("Source_Name", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sources.
    '''</summary>
    Friend Shared ReadOnly Property Sources() As String
        Get
            Return ResourceManager.GetString("Sources", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Specific.
    '''</summary>
    Friend Shared ReadOnly Property Specific() As String
        Get
            Return ResourceManager.GetString("Specific", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Specified URL is not valid..
    '''</summary>
    Friend Shared ReadOnly Property Specified_URL_is_not_valid() As String
        Get
            Return ResourceManager.GetString("Specified_URL_is_not_valid", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Standard.
    '''</summary>
    Friend Shared ReadOnly Property Standard() As String
        Get
            Return ResourceManager.GetString("Standard", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Studio.
    '''</summary>
    Friend Shared ReadOnly Property Studio() As String
        Get
            Return ResourceManager.GetString("Studio", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Subtitle  Streams.
    '''</summary>
    Friend Shared ReadOnly Property Subtitle_Streams() As String
        Get
            Return ResourceManager.GetString("Subtitle_Streams", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Subtitles.
    '''</summary>
    Friend Shared ReadOnly Property Subtitles() As String
        Get
            Return ResourceManager.GetString("Subtitles", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tagline.
    '''</summary>
    Friend Shared ReadOnly Property Tagline() As String
        Get
            Return ResourceManager.GetString("Tagline", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The name you are attempting to use for this XBMC installation is already in use. Please choose another..
    '''</summary>
    Friend Shared ReadOnly Property The_name_you_are_attempting_to_use_for_this_XBMC_installation_is_already_in_use() As String
        Get
            Return ResourceManager.GetString("The_name_you_are_attempting_to_use_for_this_XBMC_installation_is_already_in_use", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Themes.
    '''</summary>
    Friend Shared ReadOnly Property Themes() As String
        Get
            Return ResourceManager.GetString("Themes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This will remove the Language from all Genres. Are you sure?.
    '''</summary>
    Friend Shared ReadOnly Property This_will_remove_the_Language_from_all_Genres_Are_you_sure() As String
        Get
            Return ResourceManager.GetString("This_will_remove_the_Language_from_all_Genres_Are_you_sure", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Title:.
    '''</summary>
    Friend Shared ReadOnly Property Title() As String
        Get
            Return ResourceManager.GetString("Title", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Trailer.
    '''</summary>
    Friend Shared ReadOnly Property Trailer() As String
        Get
            Return ResourceManager.GetString("Trailer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TV.
    '''</summary>
    Friend Shared ReadOnly Property TV() As String
        Get
            Return ResourceManager.GetString("TV", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TV Image Selection.
    '''</summary>
    Friend Shared ReadOnly Property TV_Image_Selection() As String
        Get
            Return ResourceManager.GetString("TV_Image_Selection", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TV Show Theme.
    '''</summary>
    Friend Shared ReadOnly Property TV_Show_Theme() As String
        Get
            Return ResourceManager.GetString("TV_Show_Theme", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to TV Shows.
    '''</summary>
    Friend Shared ReadOnly Property TV_Shows() As String
        Get
            Return ResourceManager.GetString("TV_Shows", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unhandled Exception.
    '''</summary>
    Friend Shared ReadOnly Property Unhandled_Exception() As String
        Get
            Return ResourceManager.GetString("Unhandled_Exception", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unknown.
    '''</summary>
    Friend Shared ReadOnly Property Unknown() As String
        Get
            Return ResourceManager.GetString("Unknown", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unknown Movie ({0}).
    '''</summary>
    Friend Shared ReadOnly Property Unknown_Movie_Param() As String
        Get
            Return ResourceManager.GetString("Unknown_Movie_Param", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unlock.
    '''</summary>
    Friend Shared ReadOnly Property Unlock() As String
        Get
            Return ResourceManager.GetString("Unlock", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unlock All.
    '''</summary>
    Friend Shared ReadOnly Property Unlock_All() As String
        Get
            Return ResourceManager.GetString("Unlock_All", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unmark.
    '''</summary>
    Friend Shared ReadOnly Property Unmark() As String
        Get
            Return ResourceManager.GetString("Unmark", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Use Custom Size.
    '''</summary>
    Friend Shared ReadOnly Property Use_Custom_Size() As String
        Get
            Return ResourceManager.GetString("Use_Custom_Size", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Use During Automated Scrapers.
    '''</summary>
    Friend Shared ReadOnly Property Use_During_Automated_Scrapers() As String
        Get
            Return ResourceManager.GetString("Use_During_Automated_Scrapers", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Use if no Fanart Found.
    '''</summary>
    Friend Shared ReadOnly Property Use_if_no_Fanart_Found() As String
        Get
            Return ResourceManager.GetString("Use_if_no_Fanart_Found", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Use Image Cache.
    '''</summary>
    Friend Shared ReadOnly Property Use_Image_Cache() As String
        Get
            Return ResourceManager.GetString("Use_Image_Cache", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Use Native Resolution.
    '''</summary>
    Friend Shared ReadOnly Property Use_Native_Resolution() As String
        Get
            Return ResourceManager.GetString("Use_Native_Resolution", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Username:.
    '''</summary>
    Friend Shared ReadOnly Property Username() As String
        Get
            Return ResourceManager.GetString("Username", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Valid Video Extensions.
    '''</summary>
    Friend Shared ReadOnly Property Valid_Video_Extensions() As String
        Get
            Return ResourceManager.GetString("Valid_Video_Extensions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Video.
    '''</summary>
    Friend Shared ReadOnly Property Video() As String
        Get
            Return ResourceManager.GetString("Video", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Video Stream.
    '''</summary>
    Friend Shared ReadOnly Property Video_Stream() As String
        Get
            Return ResourceManager.GetString("Video_Stream", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Video Streams.
    '''</summary>
    Friend Shared ReadOnly Property Video_Streams() As String
        Get
            Return ResourceManager.GetString("Video_Streams", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} Votes.
    '''</summary>
    Friend Shared ReadOnly Property Votes() As String
        Get
            Return ResourceManager.GetString("Votes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to WARNING: Using the Expert Mode Cleaner could potentially delete wanted files. Take care when using this tool..
    '''</summary>
    Friend Shared ReadOnly Property WARNING__Using_the_Expert_Mode_Cleaner() As String
        Get
            Return ResourceManager.GetString("WARNING__Using_the_Expert_Mode_Cleaner", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whitelist Video Extensions.
    '''</summary>
    Friend Shared ReadOnly Property Whitelist_Video_Extensions() As String
        Get
            Return ResourceManager.GetString("Whitelist_Video_Extensions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Whitelisted Extensions:.
    '''</summary>
    Friend Shared ReadOnly Property Whitelisted_Extensions() As String
        Get
            Return ResourceManager.GetString("Whitelisted_Extensions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Wide.
    '''</summary>
    Friend Shared ReadOnly Property Wide() As String
        Get
            Return ResourceManager.GetString("Wide", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Width:.
    '''</summary>
    Friend Shared ReadOnly Property Width() As String
        Get
            Return ResourceManager.GetString("Width", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Writers.
    '''</summary>
    Friend Shared ReadOnly Property Writers() As String
        Get
            Return ResourceManager.GetString("Writers", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to X-Large.
    '''</summary>
    Friend Shared ReadOnly Property X_Large() As String
        Get
            Return ResourceManager.GetString("X_Large", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XBMC.
    '''</summary>
    Friend Shared ReadOnly Property XBMC() As String
        Get
            Return ResourceManager.GetString("XBMC", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to XBMC Communication.
    '''</summary>
    Friend Shared ReadOnly Property XBMC_Communication() As String
        Get
            Return ResourceManager.GetString("XBMC_Communication", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Year.
    '''</summary>
    Friend Shared ReadOnly Property Year() As String
        Get
            Return ResourceManager.GetString("Year", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You have selected {0} folders to open. Are you sure you want to do this?.
    '''</summary>
    Friend Shared ReadOnly Property You_have_selected_folders_to_open__Are_you_sure_you_want_to_do_this() As String
        Get
            Return ResourceManager.GetString("You_have_selected_folders_to_open__Are_you_sure_you_want_to_do_this", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You must enter a name for this XBMC installation..
    '''</summary>
    Friend Shared ReadOnly Property You_must_enter_a_name_for_this_XBMC_installation() As String
        Get
            Return ResourceManager.GetString("You_must_enter_a_name_for_this_XBMC_installation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You must enter a port for this XBMC installation..
    '''</summary>
    Friend Shared ReadOnly Property You_must_enter_a_port_for_this_XBMC_installation() As String
        Get
            Return ResourceManager.GetString("You_must_enter_a_port_for_this_XBMC_installation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to You must enter an IP for this XBMC installation..
    '''</summary>
    Friend Shared ReadOnly Property You_must_enter_an_IP_for_this_XBMC_installation() As String
        Get
            Return ResourceManager.GetString("You_must_enter_an_IP_for_this_XBMC_installation", resourceCulture)
        End Get
    End Property
End Class
